### PR TITLE
Upgrade to 1.16

### PR DESCRIPTION
**Pull request by Combustible**
Relatively basic upgrade to 1.16. I added some variables for the new mobs and it seems to work, can summon mobs including the new piglins and manipulate spawners. 

Would need a version bump / etc...

### CODE REVIEW

**Comment by Combustible** [comment]
If you're looking for a version of NBTEditor you can use on 1.16 before this gets merged, you can download this one here - https://files.playmonumenta.com/nbteditor-3.2-1.16-SNAPSHOT-2020-10-25.jar

**Comment by Combustible** [comment]
Bunch more changes pushed that are needed for 1.16: 

- They replaced UUIDMost / UUIDLeast with an array of 4x integers stored in UUID
- They renamed the attribute modifiers to snake_case
- Stacked mob summoning has been broken since at least 1.15, this fixes that
- Also fixes right clicking with a BoS triggering LEFT_CLICK_AIR for some annoying reason, also since 1.15+

**Comment by Combustible** [comment]
Updated previous comment with new link to new .jar for people who want it before this gets merged.

**Comment by mibby** [comment]
@Combustible Getting this error using this command on a custom diamond sword with a specific CustomModelData.

```
[09:07:19] [Server thread/INFO]: player issued server command: /nbti mod add AttackSpeed 1 16 mainhand
[09:07:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'nbti mod add AttackSpeed 1 16 mainhand' in com.goncalomb.bukkit.mylib.command.InternalCommand(nbtitem)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1921) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1732) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at xuan.cat.xuancatapi.code.paper.v1_16_R2.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:753) ~[?:?]
	at xuan.cat.xuancatapi.code.paper.v1_16_R2.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:604) ~[?:?]
	at xuan.cat.xuancatapi.code.paper.v1_16_R2.nms.entity.CodeExtendPlayerConnection.a(CodeExtendPlayerConnection.java:82) ~[?:?]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1192) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.goncalomb.bukkit.mylib.command.MySubCommand.invokeExeMethod(MySubCommand.java:203) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:122) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:112) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:112) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.InternalCommand.execute(InternalCommand.java:43) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	... 20 more
Caused by: java.lang.NullPointerException
	at com.goncalomb.bukkit.nbteditor.nbt.attributes.ItemModifier.toNBT(ItemModifier.java:90) ~[?:?]
	at com.goncalomb.bukkit.nbteditor.nbt.attributes.ItemModifier.setItemStackModifiers(ItemModifier.java:64) ~[?:?]
	at com.goncalomb.bukkit.nbteditor.commands.CommandNBTItem.mod_add(CommandNBTItem.java:96) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.invokeExeMethod(MySubCommand.java:197) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:122) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:112) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.MySubCommand.execute(MySubCommand.java:112) ~[?:?]
	at com.goncalomb.bukkit.mylib.command.InternalCommand.execute(InternalCommand.java:43) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Tuinity-"f7b8e25"]
	... 20 more
```

Otherwise seems to work on a vanilla diamond sword. Using nbteditor-3.2-1.16-SNAPSHOT-2020-10-25.jar

**Comment by Combustible** [comment]
Will take a look sometime in the next week. the only other two issues I know about are /bos getempty books don't currently work, and /bos var offers doesn't work either. 

Mojang changed a ton of the internal names of things - any BoS books from an older version of NBTEditor are going to be broken, you'll have to make new ones from scratch. There's no current way to upgrade unfortunately.

Looks like that error you got is from something I added though, can probably fix it when I have time next week.

**Comment by goncalomb** [comment]
Thanks, I'm merging this to mc-1.16.

**Pull request merged**
